# Site settings
baseurl = "http://johnnyjanzen.github.io/mmucan/"
languageCode = "en-us"
title = "MMUC"
theme = "hugo-agency-theme"
# Enter your tracking code to enable Google Analytics
googleAnalytics = ""

[params]

	# You can use Markdown syntax for urls [text](//url.to/source) or
	# most longer texts.
	#
	# All icons using Fontawesome's icon font. Look at fortawesome.github.io/Font-Awesome/icons/
	# for more icons. The icons are represented by their corresponding
	# CSS class.

	# To provide some metadata for search engines feel free to add a few
    # information about you and your website.
	name = "Your name"
	description = "Your description"

	# Since this template is static, the contact form uses www.formspree.io as a
	# proxy. The form makes a POST request to their servers to send the actual
	# email. Visitors can send up to a 1000 emails each month for free.
    #
    # What you need to do for the setup?
    #
    # - set your email address under 'email' below
    # - upload the generated site to your server
    # - send a dummy email yourself to confirm your account
    # - click the confirm link in the email from www.formspree.io
    # - you're done. Happy mailing!
	email = "your@email.com"


	# Navigation
	[params.navigation]
		brand = "Music Mission Ukraine Canada"
		statement = "Statement"
		services = "Ministries"
		portfolio = "Prayer"
		about = "About"
		team = "Team"
		calendar = "Tour"
		contact = "Contact & Donate"


	# Hero section
	[params.hero]
		# To change the background image of the hero, replace 'header-bg.jpg' in
		# the 'static/img' folder.
		title = "Kyiv Symphony Orchestra and Chorus"
		subtitle = "Music Mission Ukraine Canada"
		subsubtitle = "Wes and Kim Janzen"
		buttonText = "Tell me more"


	# Services section
	[params.services]
		title = "Ministries"
		subtitle = "MMUC works in a number of areas of need."

        [[params.services.row]]

            [[params.services.row.list]]
                icon = "fa-group"
                title = "Internally Displaced People"
                description = "Since 2014, Music Mission Ukraine has been caring for thousands of internally displaced Ukrainians.  These are people who have fled their homes, often with only the clothes on their back because of the war raging in Ukraine.  Some live in Kyiv.  Others live near the war zone.  MMUC sends blankets, Bibles, candles, food, medications and other essential living supplies to those in need.  Many of these are elderly widows.  Programs serving internally displaced people in Kyiv include members of KSOC, who bring comfort through prayers, music, Bible and music education activities for IDP children."

								[[params.services.row.list]]
		                icon = "fa-music"
		                title = "Kyiv Symphony Orchestra and Chorus (KSOC)"
		                description = "The Kyiv Symphony Orchestra and Chorus (KSOC) is the musical arm of MMUC.  KSOC shares friendship evangelism concerts throughout Ukraine.  Recently Music Mission Ukraine Canada sponsored concerts in Ukraine including Zaparozhe, Lviv, Irpin and Lutsk.  KSOC also travels to Canada from time to time to share the gospel and stories of God’s grace."

            [[params.services.row.list]]
                icon = "fa-book"
                title = "Evangelism and discipleship"
                description = "Evangelism and discipleship are core to all Music Mission Ukraine Canada activities.  Bible distribution and Bible teaching are part of all of our programs.  All friendship-evangelism outreach concerts of the Kyiv Symphony Orchestra and Chorus are rich in Biblical content.  Many concerts are sung in the Ukrainian language, with words projected on large screen to enhance clarity and understanding.  MMUC missionary Kim Janzen currently leads a weekly prayer meeting of widows, a weekly “Experiencing God” Bible study for pensioners, and two Saturday morning Bible lessons that reach over 400 pensioners each week, and a weekly Bible study for youth."


								[[params.services.row.list]]
										icon = "fa-child"
										title = "Young Widows"
										description = "Music Mission Ukraine Canada is also reaching out to a whole new generation of widows who have lost husbands in the recent war.  "

								[[params.services.row.list]]
										icon = "fa-globe"
										title = "Bible distribution, preaching and teaching "
										description = "The Christian faith is clearly presented in the sacred Holy Bible.  Sharing these scriptures is part of the work of Music Mission Ukraine Canada.  The Bible in various languages, versions and styles such as large print Bibles for the sight impaired, or colourful illustrated  Bibles for children, are readily available through the Ukrainian Bible Society in Kyiv.  Music Mission Ukraine Canada missionaries Wes and Kim Janzen preach and teach from the Bible each week.  Their calling is to share the glorious gospel of the Lord Jesus Christ with others."

								[[params.services.row.list]]
										icon = "fa-eye"
										title = "Eye care for widows and internally displaced people"
										description = "A Music Mission Ukraine Canada eye doctor working in Kyiv cares for internally displaced people and widows, in the city of Kyiv.  Through this important outreach many can now see clearly and also obtain appropriate medical referrals for other medical needs.  Prescription eye glasses are ordered locally in Kyiv for a fraction of what they would cost in Canada.  "

	# Portfolio section
	[params.portfolio]
		# All projects defined in their own files. You can find example projects
		# at 'exampleSite/data/projects'. Copy the 'projects' folder into the 'data' directory
		# at the root of this Hugo site.
		# For more informtion take a look at the README.
		title = "Prayer"
		subtitle = "Ministry updates and prayer requests."

		[params.portfolio.modal]
            client = "Client"
            date = "Date"
            category = "Category"
            buttonText = "Close project"


    # About section
	[params.about]
		title = "Our Story"
		subtitle = "By God's Grace."
		endpoint = "Be part<br>of our<br>story!"

		# The events will be listed from the top to the bottom.
		# All images are stored under 'static/img/about'.
		# Replace them with your own.
		[[params.about.events]]
			img = "2006.jpg"
			date = "2006"
			title = "Early Concert Collaborations"
			description = "Wes Janzen guest conducted Kyiv Symphony Orchestra and Chorus for the first time in their first-ever performance of Haydn Creation.  This sacred masterpiece, taken from the Bible and Milton’ Paradise Lost, brought tears of joy to  Kyiv Symphony Orchestra and Chorus musicians.  Creation was essentially new to them as it had been previously suppressed by communist authorities.  After this first project with Kyiv Symphony Orchestra and Chorus, Wes returned to Kyiv each year, with duration of visits increasing year by year.  Wes and Kim Janzen continued to serve Missions Fest Vancouver and teach at Trinity Western University."

		[[params.about.events]]
			img = "2007.jpg"
			date = "2007"
			title = "Kim and Wes Janzen went to Kyiv for the first time together."
			description = "They also delighted in Kyiv Symphony Orchestra and Chorus outreach to the poor and needy.  They witnessed an extraordinary outreach to widows and orphans.  Wes was appointed Principle Guest Conductor of the Kyiv Symphony Orchestra and Chorus.  Kim participated through singing and began to teach Bible lessons on a regular basis to widows, orphans and children."

		[[params.about.events]]
			img = "2008.jpg"
			date = "2008-2012"
			title = "Continued short-term work."
			description = "The Janzen family continued to serve as “short term” missionary volunteers in Ukraine.  Kim’s work as mentor and Bible teacher expanded significantly.  Wes continued to conduct many KSOC performances, preach and teach.  Several visits are thanks  to Trinity Western University graciously allowing times for summer scholarly activity (conducting) and granting several leaves of absence."

		[[params.about.events]]
			img = "2012.jpg"
			date = "2012"
			title = "Transitions"
			description = "Kim was appointed Interim Director of Outreach Ministries and Wes Interim Conductor and Artistic Director of Kyiv Symphony Orchestra and Chorus and Interim President of Music Mission Kiev."

			[[params.about.events]]
				img = "2012b.jpg"
				date = "2012"
				title = "International Concerts"
				description = "Wes Janzen brought Kyiv Symphony Orchestra and Chorus to Tallin, Estonia for a major summer missions conference.  In fall, Wes and Kim Janzen brought Kyiv Symphony Orchestra and Chorus to Canada for the first time."

				[[params.about.events]]
					img = "2013.jpg"
					date = "2013"
					title = "Leap of Faith"
					description = "In November, Wes and Kim Janzen accepted full time missionary positions in Ukraine and Wes announced his early retirement from Trinity Western University.  Kim was appointed Associate Director of Outreach Ministries, Wes Conductor and Artistic Director of Kyiv Symphony Orchestra and Chorus and President of Music Mission Kiev and Director of Music Mission Ukraine Canada."

					[[params.about.events]]
						img = "2014.jpg"
						date = "2014"
						title = "International Concerts"
						description = "Wes and Kim Janzen brought 42 members of Kyiv Symphony Orchestra and Chorus across Canada, sharing music, the gospel of Jesus Christ, and stories of God’s grace.  The ministries of Music Mission Ukraine Canada were shared with many Canadians.  Prof. Dr. Wes Janzen was appointed Professor Emeritus, Trinity Western University."

						[[params.about.events]]
							img = "2015.png"
							date = "2015"
							title = "Ukrainian Outreach"
							description = "Music Mission Ukraine Canada contributed uniquely to the outreach of Kyiv Symphony Orchestra and Chorus, with friendship evangelism concerts going beyond Kyiv to other cities in Ukraine for the first time.  The gospel was shared through music and the spoken word in Zaparojhe, Lviv, Irpin and Lutsk.  Music Mission Ukraine Canada embraced another unique and new outreach, serving thousand of internally displaced people who fled their homes due to foreign aggression and war."


	# Team section
	[params.team]
		title = "Our amazing team"
		subtitle = ""
		description = ""

		# All team member's pictures are stored under 'static/img/team'.
		# Replace them with your own too.
		[[params.team.members]]
			img = "Kim.jpg"
			name = "Kim Janzen"
			position = "Missionary"
			social = [
			#	["fa-twitter", "#"],
			#	["fa-facebook", "#"],
			#	["fa-linkedin", "#"]
			]

		[[params.team.members]]
			img = "Wes.jpg"
			name = "Wes Janzen"
			position = "Missionary"
			social = [
			#	["fa-twitter", "#"],
			#	["fa-facebook", "#"],
			#	["fa-linkedin", "#"]
			]

			[[params.team.members]]
				img = "Ksoc.jpg"
				name = "KSOC"
				position = "Kyiv Symphony Orchestra and Chorus"
				social = [
]
		[[params.team.members]]
			img = "Board.jpg"
			name = "MMUC Board"
			position = "Board"
			social = [
			#	["fa-twitter", "#"],
			#	["fa-facebook", "#"],
			#	["fa-linkedin", "#"]
			]

#Statement Section

			[params.statement]
				title = "Mission Statement"
				subtitle = ""
				description = "Music Mission Ukraine Canada (MMUC) exists to proclaim the gospel of Jesus Christ and to provide humanitarian assistance to the needy, including internally displaced people, widows and orphans in Ukraine.  Through Bibles, great sacred classical musical masterpieces that come from scripture, Bible studies and camps, educational programs, Biblical preaching, teaching and discipleship, MMUC is spreading the gospel of Jesus Christ.  Through Ukrainian musicians in the Kyiv Symphony Orchestra and Chorus (KSOC) the gospel is shared through friendship-evangelism concerts in Ukraine and sacred concerts in Canada.   Through MMUC, needy Ukrainians receive humanitarian assistance in the form of food, clothing, blankets, medicine, eye care, shelter and other essential living supplies."

				[params.calendar]
					title = "Tour Dates"
					subtitle = ""




	# Client section
	# All the clients' logos are stored under 'static/img/logos'.
	# Replace them with your clients's logos.
	#[[params.clients]]
	#	logo = "envato.jpg"
	#	link = "#"

	#[[params.clients]]
	#	logo = "designmodo.jpg"
	#	link = "#"

	#[[params.clients]]
	#	logo = "themeforest.jpg"
	#	link = "#"

	#[[params.clients]]
	#	logo = "creative-market.jpg"
	#	link = "#"


	# Contact section
	[params.contact]
		title = "Contact & Donate"
		subtitle  = "Subscribe to our mailing list."
		donateText = "Please send your donation, clearly marked “Music Mission Ukraine Canada” in the memo line to Multination Missions Foundation, P. O. Box 2401, Abbotsford, BC, V3T 4X3  or phone Helmut Wiens at 778 549 8031 to make a credit card donation.  Donations are tax deductible.  Music Mission Ukraine Canada is an agent of Multi Nation Missions Foundation.  MMF is a Canadian Charitable Organization. BN Regd. N. 80737560RR0001."



		# 'warning' defines error messages for invalid inputs
		[params.contact.form.name]
			text = "Your Name *"
			warning = "Please enter your name."

		[params.contact.form.email]
			text = "Your Email *"
			warning = "Please enter your email address."

		[params.contact.form.phone]
			text = "Your Phone *"
			warning = "Please enter your phone number."

		[params.contact.form.message]
			text = "Your Message *"
			warning = "Please enter a message."


	# Footer section
	[params.footer]
		copyright = "© 2016"

#		[[params.footer.social]]
#			icon = "fa-twitter"
#			link = "#"

	#	[[params.footer.social]]
	#		icon = "fa-facebook"
	#		link = "#"

	#	[[params.footer.social]]
	#		icon = "fa-linkedin"
	#		link = "#"

	#	[[params.footer.quicklinks]]
	#		text = ""
	#		link =""
